### ISSUE TITLE
getting a 404 error from Vagrant Cloud for bento/ubuntu-19.10

### ISSUE THREAD

**Issue by RichMorin** [chef/bento#1270]
# Version:

NA

# Environment:

NA

# Scenario:

I'm trying to download and use bento/ubuntu-19.10 from the Vagrant Cloud, using `vagrant init` and `vagrant up`.

# Steps to Reproduce:

    vagrant init bento/ubuntu-19.10 --minimal --box-version '202001.16.0'
    vagrant up --provision

# Expected Result:

Vagrant should provision the box.

# Actual Result:

Vagrant gets a 404 error from the web server.
See https://gist.github.com/RichMorin/687a540e7448ce0a99d19482d3f886cb for output.

**Comment by svpernova09** [comment]
Can confirm:

```
└── vagrant box add bento/ubuntu-19.10                                                                                                                     
==> box: Loading metadata for box 'bento/ubuntu-19.10'
    box: URL: https://vagrantcloud.com/bento/ubuntu-19.10
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) parallels
2) virtualbox
3) vmware_desktop

Enter your choice: 2
==> box: Adding box 'bento/ubuntu-19.10' (v202001.16.0) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-19.10/versions/202001.16.0/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

Could be an S3 issue.

**Comment by svpernova09** [comment]
Currently downloading the Parallels provider, so this is either a Virtualbox specifc issue with this release or an isolated S3 issue.

**Comment by RichMorin** [comment]
I just updated to '202002.04.0', which loads OK (whew!).  That said, I find it disturbing that this issue has not been triaged in over two weeks; it only seems to have been resolved in the ongoing course of updates. Was this the wrong place to file the issue? If so, what is the right place? If not, can something be done to make the process more responsive?

**Comment by tas50** [comment]
It's all just a matter of folks and priorities. It looks like Hashi had some issue with the S3 backing of the file. I pushed up the new one to resolve the issue. I rebuilt all the images while I was in there. We aim for quick response, but it's not always a possibility

**Comment by svpernova09** [comment]
> I just updated to '202002.04.0', which loads OK (whew!). That said, I find it disturbing that this issue has not been triaged in over two weeks; it only seems to have been resolved in the ongoing course of updates. Was this the wrong place to file the issue? If so, what is the right place? If not, can something be done to make the process more responsive?

To be fair I confirmed your issue within 5 minutes and followed up with the idea it's probably the specific box itself. So while the untriaged tag was still here, the root cause was identified. 

If this happens again feel free to build the image yourself until someone with upload ability can update the image from this project. I'm happy to answer whatever questions I can if you run into issues building the boxes yourself.

**Comment by RichMorin** [comment]
As an open source developer, I totally understand that support resources are not unlimited. However, there is still an issue of transparency. Two weeks in, I had no idea if anyone (aside from @supernova09, whom I had thought was "just another user") had even read my issue. And, even when the new version was pushed, no response was filed to the issue. So, I only found out about the update by trying another download. All that said, thanks to @tas50 for resolving the issue!

**Comment by svpernova09** [comment]
@RichMorin I am in fact just another user :D

I try to help out here and triage stuff when I can. Just trying to pay it forward.
