### ISSUE TITLE
Centos Stream 9 template

### ISSUE THREAD

**Issue by elreydetoda** [chef/bento#1391]
### Describe the Enhancement:
Trying to add a centos stream 9 template, but unfortunately the mirrors aren't providing a hash for the symlinked latest file: `CentOS-Stream-9-latest-x86_64-dvd1.iso` as you can see in the picture below.

![image](https://user-images.githubusercontent.com/10230166/152692602-879f7ad8-686a-4252-8e07-dafa05e76e76.png)

### Describe the Need:
There needs to be a consistent way of getting the needed information to populate a template.

### Current Alternative
there is some interaction with upstream again ([like last time](https://github.com/chef/bento/pull/1361#issuecomment-852475135)) to have this resolved

### Can We Help You Implement This?:
I don't think so yet, I'm going to engage @hashicorp's packer team to see if they can implement an http data source for the new packer HCL. If this project isn't apposed to it, I'd like to work on a HCL alternative for building the CentOS stream image. Once the http data source is implemented I should be able to use string manipulation functions with packer's HCL to substitute the needed characters in so the checksums will match the ISO name.  Because the two ISOs are the same:

related: #1361 #1368 @ramereth (since he's contributed CentOS stream stuff before)

**Comment by ramereth** [comment]
Looks like there's an upstream [bug](https://bugzilla.redhat.com/show_bug.cgi?id=2027833) already filed for this that you can track.

**Comment by ramereth** [comment]
@elreydetoda It looks like this was resolved upstream: https://bugzilla.redhat.com/show_bug.cgi?id=2027833#c2

Can you please confirm this works for you now?

**Comment by elreydetoda** [comment]
Thanks @ramereth ! I think it should be fine for this project if I switch to the one that they are appending with .SHA256SUM, but good call on letting them know the file isn't fixed for that one yet.

**Comment by elreydetoda** [comment]
So, for now till https://github.com/hashicorp/packer-plugin-qemu/issues/63 gets resolved, we can at least plug in a specific mirror and have everything build properly. I guess what is the best mirror for the bento project, this is what came back for me:

```console
$ curl -sSw '%{redirect_url}' -o /dev/null 'https://mirrors.centos.org/mirrorlist?path=/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-latest-x86_64-dvd1.iso.SHA256SUM&redirect=1&protocol=https' ; echo
https://ftp-osl.osuosl.org/pub/centos-stream/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-latest-x86_64-dvd1.iso.SHA256SUM
$ curl -sSw '%{redirect_url}' -o /dev/null 'https://mirrors.centos.org/mirrorlist?path=/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-latest-x86_64-dvd1.iso&redirect=1&protocol=https' ; echo 
https://ord.mirror.rackspace.com/centos-stream/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-latest-x86_64-dvd1.iso

**Comment by jaymzh** [comment]
This would be very useful.

**Comment by Stromweld** [comment]
box released at https://app.vagrantup.com/bento/boxes/centos-stream-9/versions/202301.20.0
